baseURL = 'https://ttig217.github.io/phrase/'
languageCode = 'zh-tw'
title = 'imToken Phrase Blog'
author = 'Irara'
theme = 'contrast-hugo'

[params]
  minimal = false
  excerpts = false
  description = "my blog"